permalink: /:year:month:day/:title
url: https://mathco.me
baseurl: /

# variables
name: mathC0.
description: mathCo area........
google_verification: null
gems: [jekyll-sitemap]

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true